apiVersion: v1
kind: ServiceAccount
metadata:
  name: ppm-keyvault-sa
  labels:
    app: ppm-api
  annotations:
    azure.workload.identity/client-id: "${KEY_VAULT_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
