plan_id: plan-b9c70b75-365c-44c3-ada4-346077042f83
tasks:
- task_id: task-1
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:27:31.192046Z'
version: 204
