plan_id: plan-880811a9-7371-41d7-8f39-e1d70a2666b0
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T09:59:27.235068Z'
version: 338
