plan_id: plan-219b67e0-d3db-4025-81ca-50b72c0e0bcc
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T03:28:15.880918Z'
version: 30
