plan_id: plan-a7a30bce-fb20-40b2-9888-e1c85d206fe9
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T03:36:36.790984Z'
version: 76
