plan_id: plan-9853af44-0c31-4520-9825-754a929f89e6
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T08:37:11.259127Z'
version: 265
