plan_id: plan-0a8cdb58-d3f5-45ea-a3a3-9fdcbab50da4
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T10:37:04.650756Z'
version: 357
