plan_id: plan-938d9c9f-a4de-4009-a629-6ec9a9c64844
tasks:
- task_id: task-1
  agent_id: schedule-planning
  action: get_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_query
- task_id: task-2
  agent_id: schedule-planning
  action: update_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_update
status: approved
modification_history: []
created_at: '2026-02-27T11:55:42.883413Z'
version: 477
