plan_id: plan-1b195c65-4ff9-4499-8ff8-7c6f02a48041
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management
  action: null
  dependencies:
  - financial-management
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T11:48:19.490312Z'
version: 443
