plan_id: plan-74b1ff80-fc57-469f-9955-e8fc2538604a
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T11:57:21.391907Z'
version: 480
