plan_id: plan-1583da7f-e3c0-4bee-ad1f-288ae00b8ca2
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:18:35.758210Z'
version: 151
