plan_id: plan-500b861c-612b-49b0-9808-571f23a6bebb
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T11:37:24.285019Z'
version: 415
