plan_id: plan-9a874749-d198-45c2-91f1-b1857008da71
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-25T16:03:48.859176Z'
version: 246
