plan_id: plan-50564805-36c9-40bd-b6ce-972ac1c22ad5
tasks:
- task_id: task-1
  agent_id: schedule-planning-agent
  action: get_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_query
- task_id: task-2
  agent_id: schedule-planning-agent
  action: update_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_update
status: approved
modification_history: []
created_at: '2026-02-22T05:23:55.961788Z'
version: 189
