plan_id: plan-85d718c7-4d5a-4984-8013-383a5bd25e94
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:22:16.257544Z'
version: 176
