plan_id: plan-bf02a538-958c-4336-8bd0-527968d55b51
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T11:57:23.591622Z'
version: 484
