plan_id: plan-3b6de128-21e4-4ddb-9486-0251ee105f18
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T03:26:34.452486Z'
version: 22
