plan_id: plan-b9ae5f1b-2fec-420a-9a0f-c12968fb2d37
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:02:57.706832Z'
version: 132
