plan_id: plan-e4eb5254-2113-4e8e-be5f-c028960c1f9a
tasks:
- task_id: task-1
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T03:29:52.351257Z'
version: 43
