plan_id: plan-3a32a39d-0207-4748-827a-dfb7ef762f9f
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-25T16:03:49.409604Z'
version: 248
