plan_id: plan-f4727d99-cb05-473d-a529-d1bb9c9d168b
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T08:38:27.928078Z'
version: 273
