plan_id: plan-092cead2-6bfc-4715-9eb3-dc7cacdbfb98
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T03:28:16.015910Z'
version: 33
