plan_id: plan-0f7f9a09-6f79-4c29-9024-d1ed9a32d407
tasks:
- task_id: task-1
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T12:03:47.013196Z'
version: 506
