plan_id: plan-1363008e-e9fa-49c9-9355-5c6d69d0bd1f
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies:
  - risk-management
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management
  action: null
  dependencies:
  - financial-management
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T09:53:31.849317Z'
version: 332
