plan_id: plan-1f27dec8-643d-411d-9a38-95d5f151827f
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T08:37:11.590271Z'
version: 266
