plan_id: plan-35db3a77-d3e6-473c-baf5-0ee27fb319aa
tasks:
- task_id: task-1
  agent_id: schedule-planning-agent
  action: get_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_query
- task_id: task-2
  agent_id: schedule-planning-agent
  action: update_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_update
status: approved
modification_history: []
created_at: '2026-02-27T11:34:25.178161Z'
version: 405
