plan_id: plan-265addda-2eff-4b4f-aa47-1364d7d2155c
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:22:16.660252Z'
version: 178
