plan_id: plan-142f0e68-323a-4a46-985f-8d4c51345354
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies:
  - risk-management
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management-agent
  action: null
  dependencies:
  - financial-management
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T08:38:30.161311Z'
version: 278
