plan_id: plan-371a97a5-5c4d-40bf-90d1-a24982e7e8c5
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T04:00:01.885496Z'
version: 95
