plan_id: plan-52003a1d-ed9e-4a69-bfcf-fccfbf98ac4f
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T11:44:48.119518Z'
version: 428
