plan_id: plan-c2fbcd47-4978-43f9-8016-d664f761eec4
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T13:11:10.504040Z'
version: 567
