plan_id: plan-f1e064e7-4140-4152-960f-2176842299b9
tasks:
- task_id: task-1
  agent_id: financial-management-agent
  action: null
  dependencies:
  - risk-management
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management-agent
  action: null
  dependencies:
  - financial-management
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T13:03:25.354761Z'
version: 523
