plan_id: plan-1186930e-4021-4d67-a9f8-0ccf84232875
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:29:11.756300Z'
version: 213
