plan_id: plan-6a1092c9-8343-4ccc-a320-6a54bd39b53f
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T06:02:14.694476Z'
version: 235
