plan_id: plan-901442ed-2282-451c-a27c-9fc016cc099b
tasks:
- task_id: task-1
  agent_id: schedule-planning-agent
  action: get_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_query
- task_id: task-2
  agent_id: schedule-planning-agent
  action: update_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_update
status: approved
modification_history: []
created_at: '2026-02-27T13:04:56.650450Z'
version: 536
