plan_id: plan-f1f2e141-42c2-4afe-b908-4ed61352215b
tasks:
- task_id: task-1
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T10:57:53.352405Z'
version: 363
