plan_id: plan-064cab5d-212b-4b42-a109-a045d0de693a
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:23:55.223910Z'
version: 186
