plan_id: plan-c4402743-effc-4adf-a006-389bd12695a2
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T08:37:12.268212Z'
version: 268
