plan_id: plan-04d128c4-1d46-49e4-bf48-dafd5f774fbb
tasks:
- task_id: task-1
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:02:57.233499Z'
version: 129
