plan_id: plan-4e7db08f-2bb2-40ca-bbcd-624b7fa4f27f
tasks:
- task_id: task-1
  agent_id: schedule-planning
  action: get_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_query
- task_id: task-2
  agent_id: schedule-planning
  action: update_schedule
  dependencies: []
  metadata:
    priority: null
    intent: schedule_update
status: approved
modification_history: []
created_at: '2026-02-27T10:57:55.859893Z'
version: 369
