plan_id: plan-26ba06dc-51df-4053-830d-4e9aa729cb95
tasks:
- task_id: task-1
  agent_id: risk-management-agent
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:19:01.762148Z'
version: 159
