plan_id: plan-bd4ef4bd-ce78-4743-9547-1620afdd7ca5
tasks:
- task_id: task-1
  agent_id: financial-management
  action: null
  dependencies:
  - risk-management
  metadata:
    priority: null
    intent: null
- task_id: task-2
  agent_id: risk-management
  action: null
  dependencies:
  - financial-management
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-27T08:37:12.687390Z'
version: 269
