plan_id: plan-ba480470-653b-4525-8ff6-46a09497c916
tasks:
- task_id: task-1
  agent_id: risk-management
  action: null
  dependencies: []
  metadata:
    priority: null
    intent: null
status: approved
modification_history: []
created_at: '2026-02-22T05:22:15.868471Z'
version: 174
