apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-otel-collector
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/component: observability
  annotations:
    observability.ppm/otel-config: "true"
data:
  collector.yaml: |-
{{ .Files.Get "files/collector.yaml" | indent 4 }}
