{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "name" . }}-kv
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ required "keyVault.clientId is required when keyVault.enabled is true" .Values.keyVault.clientId | quote }}
    keyvaultName: {{ required "keyVault.name is required when keyVault.enabled is true" .Values.keyVault.name | quote }}
    tenantId: {{ required "keyVault.tenantId is required when keyVault.enabled is true" .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secrets.identityJwtSecret | quote }}
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secrets.policyEngineServiceToken | quote }}
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.keyVault.secretName | quote }}
      type: Opaque
      data:
        - objectName: {{ .Values.keyVault.secrets.identityJwtSecret | quote }}
          key: {{ .Values.keyVault.secrets.identityJwtSecret | quote }}
        - objectName: {{ .Values.keyVault.secrets.policyEngineServiceToken | quote }}
          key: {{ .Values.keyVault.secrets.policyEngineServiceToken | quote }}
{{- end }}
