{{- if or .Values.keyVault.enabled .Values.leaderElection.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "name" .) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
  {{- if .Values.keyVault.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ required "keyVault.clientId is required when keyVault.enabled is true" .Values.keyVault.clientId | quote }}
  {{- end }}
{{- end }}
