apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}-kv
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
  annotations:
    azure.workload.identity/client-id: {{ required "keyVault.clientId is required for audit-log" .Values.keyVault.clientId | quote }}
