apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: observability
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: otlp-grpc
    - name: otlp-http
      port: {{ .Values.service.ports.http }}
      targetPort: otlp-http
    - name: prometheus
      port: {{ .Values.service.ports.prometheus }}
      targetPort: prometheus
