/**
 * Demo data for methodology navigation
 *
 * Provides sample methodologies and a "Project Apollo" demo project
 * showing stage-gate behavior with activities in various states.
 */

import type { MethodologyMap, ProjectMethodology } from './types';

/**
 * Waterfall methodology template
 */
export const waterfallMethodology: MethodologyMap = {
  id: 'methodology-waterfall',
  name: 'Waterfall',
  description: 'Traditional sequential project management approach',
  type: 'waterfall',
  version: '1.0',
  stages: [
    {
      id: 'stage-initiation',
      name: 'Initiation',
      description: 'Define project scope, objectives, and stakeholders',
      status: 'not_started',
      prerequisites: [],
      order: 1,
      activities: [
        {
          id: 'act-charter',
          name: 'Project Charter',
          description: 'Create the project charter document',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-stakeholders',
          name: 'Stakeholder Register',
          description: 'Identify and document project stakeholders',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: ['act-charter'],
          order: 2,
        },
      ],
    },
    {
      id: 'stage-planning',
      name: 'Planning',
      description: 'Develop project management plan and baselines',
      status: 'not_started',
      prerequisites: ['stage-initiation'],
      order: 2,
      activities: [
        {
          id: 'act-wbs',
          name: 'Work Breakdown Structure',
          description: 'Decompose project scope into manageable work packages',
          status: 'not_started',
          canvasType: 'tree',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-schedule',
          name: 'Project Schedule',
          description: 'Develop the project timeline and milestones',
          status: 'not_started',
          canvasType: 'timeline',
          prerequisites: ['act-wbs'],
          order: 2,
        },
        {
          id: 'act-budget',
          name: 'Budget Plan',
          description: 'Estimate costs and create the project budget',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: ['act-wbs'],
          order: 3,
        },
      ],
    },
    {
      id: 'stage-execution',
      name: 'Execution',
      description: 'Execute project work and produce deliverables',
      status: 'not_started',
      prerequisites: ['stage-planning'],
      order: 3,
      activities: [
        {
          id: 'act-deliverables',
          name: 'Deliverables Tracker',
          description: 'Track project deliverables and their status',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: [],
          order: 1,
        },
      ],
    },
    {
      id: 'stage-monitoring',
      name: 'Monitoring & Controlling',
      description: 'Monitor and control project performance',
      status: 'not_started',
      prerequisites: [],
      alwaysAccessible: true,
      order: 4,
      activities: [
        {
          id: 'act-dashboard',
          name: 'Project Dashboard',
          description: 'Real-time project status and KPIs',
          status: 'not_started',
          canvasType: 'dashboard',
          prerequisites: [],
          alwaysAccessible: true,
          order: 1,
        },
        {
          id: 'act-risks',
          name: 'Risk Register',
          description: 'Track and manage project risks',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: [],
          alwaysAccessible: true,
          order: 2,
        },
        {
          id: 'act-issues',
          name: 'Issue Log',
          description: 'Track and resolve project issues',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: [],
          alwaysAccessible: true,
          order: 3,
        },
      ],
    },
    {
      id: 'stage-closing',
      name: 'Closing',
      description: 'Formally close the project',
      status: 'not_started',
      prerequisites: ['stage-execution'],
      order: 5,
      activities: [
        {
          id: 'act-lessons',
          name: 'Lessons Learned',
          description: 'Document lessons learned for future projects',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-closeout',
          name: 'Project Closeout Report',
          description: 'Final project report and closure documentation',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: ['act-lessons'],
          order: 2,
        },
      ],
    },
  ],
};

/**
 * Agile/Scrum methodology template
 */
export const agileMethodology: MethodologyMap = {
  id: 'methodology-agile',
  name: 'Agile Scrum',
  description: 'Iterative agile approach with sprints',
  type: 'agile',
  version: '1.0',
  stages: [
    {
      id: 'stage-product-vision',
      name: 'Product Vision',
      description: 'Define product vision and roadmap',
      status: 'not_started',
      prerequisites: [],
      order: 1,
      activities: [
        {
          id: 'act-vision',
          name: 'Product Vision Statement',
          description: 'Define the product vision',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-roadmap',
          name: 'Product Roadmap',
          description: 'High-level product timeline',
          status: 'not_started',
          canvasType: 'timeline',
          prerequisites: ['act-vision'],
          order: 2,
        },
      ],
    },
    {
      id: 'stage-backlog',
      name: 'Product Backlog',
      description: 'Create and prioritize product backlog',
      status: 'not_started',
      prerequisites: ['stage-product-vision'],
      order: 2,
      activities: [
        {
          id: 'act-user-stories',
          name: 'User Stories',
          description: 'Define user stories and acceptance criteria',
          status: 'not_started',
          canvasType: 'tree',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-backlog-prioritization',
          name: 'Backlog Prioritization',
          description: 'Prioritize and estimate backlog items',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: ['act-user-stories'],
          order: 2,
        },
      ],
    },
    {
      id: 'stage-sprints',
      name: 'Sprint Execution',
      description: 'Execute work in sprints',
      status: 'not_started',
      prerequisites: ['stage-backlog'],
      order: 3,
      activities: [
        {
          id: 'act-sprint-board',
          name: 'Sprint Board',
          description: 'Track sprint progress',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-burndown',
          name: 'Burndown Chart',
          description: 'Track sprint burndown',
          status: 'not_started',
          canvasType: 'dashboard',
          prerequisites: [],
          order: 2,
        },
      ],
    },
    {
      id: 'stage-agile-monitoring',
      name: 'Monitoring & Metrics',
      description: 'Track agile metrics and team health',
      status: 'not_started',
      prerequisites: [],
      alwaysAccessible: true,
      order: 4,
      activities: [
        {
          id: 'act-velocity',
          name: 'Velocity Dashboard',
          description: 'Track team velocity over sprints',
          status: 'not_started',
          canvasType: 'dashboard',
          prerequisites: [],
          alwaysAccessible: true,
          order: 1,
        },
        {
          id: 'act-retrospective',
          name: 'Retrospective Notes',
          description: 'Sprint retrospective documentation',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: [],
          alwaysAccessible: true,
          order: 2,
        },
      ],
    },
  ],
};

/**
 * Hybrid methodology template
 */
export const hybridMethodology: MethodologyMap = {
  id: 'methodology-hybrid',
  name: 'Hybrid',
  description: 'Combined waterfall governance with agile execution',
  type: 'hybrid',
  version: '1.0',
  stages: [
    {
      id: 'stage-governance',
      name: 'Governance Setup',
      description: 'Establish project governance framework',
      status: 'not_started',
      prerequisites: [],
      order: 1,
      activities: [
        {
          id: 'act-governance-charter',
          name: 'Project Charter',
          description: 'Formal project authorization',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-governance-plan',
          name: 'Governance Plan',
          description: 'Define governance structure and processes',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: ['act-governance-charter'],
          order: 2,
        },
      ],
    },
    {
      id: 'stage-agile-planning',
      name: 'Agile Planning',
      description: 'Set up agile execution framework',
      status: 'not_started',
      prerequisites: ['stage-governance'],
      order: 2,
      activities: [
        {
          id: 'act-hybrid-backlog',
          name: 'Product Backlog',
          description: 'Initial product backlog',
          status: 'not_started',
          canvasType: 'tree',
          prerequisites: [],
          order: 1,
        },
        {
          id: 'act-release-plan',
          name: 'Release Plan',
          description: 'High-level release timeline',
          status: 'not_started',
          canvasType: 'timeline',
          prerequisites: ['act-hybrid-backlog'],
          order: 2,
        },
      ],
    },
    {
      id: 'stage-hybrid-execution',
      name: 'Iterative Execution',
      description: 'Execute work in iterations',
      status: 'not_started',
      prerequisites: ['stage-agile-planning'],
      order: 3,
      activities: [
        {
          id: 'act-iteration-tracker',
          name: 'Iteration Tracker',
          description: 'Track iteration progress',
          status: 'not_started',
          canvasType: 'spreadsheet',
          prerequisites: [],
          order: 1,
        },
      ],
    },
    {
      id: 'stage-hybrid-monitoring',
      name: 'Monitoring & Controlling',
      description: 'Monitor project and report to stakeholders',
      status: 'not_started',
      prerequisites: [],
      alwaysAccessible: true,
      order: 4,
      activities: [
        {
          id: 'act-hybrid-dashboard',
          name: 'Executive Dashboard',
          description: 'High-level project status for stakeholders',
          status: 'not_started',
          canvasType: 'dashboard',
          prerequisites: [],
          alwaysAccessible: true,
          order: 1,
        },
        {
          id: 'act-status-reports',
          name: 'Status Reports',
          description: 'Regular status reporting',
          status: 'not_started',
          canvasType: 'document',
          prerequisites: [],
          alwaysAccessible: true,
          order: 2,
        },
      ],
    },
  ],
};

/**
 * Project Apollo - Demo project with methodology state showing gating behavior
 *
 * This demonstrates:
 * - Completed Initiation stage
 * - In-progress Planning stage
 * - Locked Execution and Closing stages (prerequisites not met)
 * - Always-accessible Monitoring & Controlling
 */
export const projectApolloMethodology: ProjectMethodology = {
  projectId: 'project-apollo',
  projectName: 'Project Apollo',
  methodology: {
    id: 'methodology-apollo',
    name: 'Waterfall',
    description: 'Traditional sequential project management approach',
    type: 'waterfall',
    version: '1.0',
    stages: [
      {
        id: 'stage-initiation',
        name: 'Initiation',
        description: 'Define project scope, objectives, and stakeholders',
        status: 'complete',
        prerequisites: [],
        order: 1,
        activities: [
          {
            id: 'act-charter',
            name: 'Project Charter',
            description: 'Create the project charter document',
            status: 'complete',
            canvasType: 'document',
            artifactId: 'artifact-charter-1',
            prerequisites: [],
            order: 1,
          },
          {
            id: 'act-stakeholders',
            name: 'Stakeholder Register',
            description: 'Identify and document project stakeholders',
            status: 'complete',
            canvasType: 'spreadsheet',
            prerequisites: ['act-charter'],
            order: 2,
          },
        ],
      },
      {
        id: 'stage-planning',
        name: 'Planning',
        description: 'Develop project management plan and baselines',
        status: 'in_progress',
        prerequisites: ['stage-initiation'],
        order: 2,
        activities: [
          {
            id: 'act-wbs',
            name: 'Work Breakdown Structure',
            description: 'Decompose project scope into manageable work packages',
            status: 'complete',
            canvasType: 'tree',
            artifactId: 'artifact-wbs-1',
            prerequisites: [],
            order: 1,
          },
          {
            id: 'act-schedule',
            name: 'Project Schedule',
            description: 'Develop the project timeline and milestones',
            status: 'in_progress',
            canvasType: 'timeline',
            artifactId: 'artifact-timeline-1',
            prerequisites: ['act-wbs'],
            order: 2,
          },
          {
            id: 'act-budget',
            name: 'Budget Plan',
            description: 'Estimate costs and create the project budget',
            status: 'not_started',
            canvasType: 'spreadsheet',
            artifactId: 'artifact-spreadsheet-1',
            prerequisites: ['act-wbs'],
            order: 3,
          },
          {
            id: 'act-risk-plan',
            name: 'Risk Management Plan',
            description: 'Identify risks and develop mitigation strategies',
            status: 'not_started',
            canvasType: 'document',
            prerequisites: ['act-schedule'],
            order: 4,
          },
          {
            id: 'act-comms-plan',
            name: 'Communications Plan',
            description: 'Define project communication approach',
            status: 'not_started',
            canvasType: 'document',
            prerequisites: [],
            order: 5,
          },
        ],
      },
      {
        id: 'stage-execution',
        name: 'Execution',
        description: 'Execute project work and produce deliverables',
        status: 'not_started',
        prerequisites: ['stage-planning'],
        order: 3,
        activities: [
          {
            id: 'act-deliverables',
            name: 'Deliverables Tracker',
            description: 'Track project deliverables and their status',
            status: 'not_started',
            canvasType: 'spreadsheet',
            prerequisites: [],
            order: 1,
          },
          {
            id: 'act-team-assignments',
            name: 'Team Assignments',
            description: 'Resource assignments and workload tracking',
            status: 'not_started',
            canvasType: 'spreadsheet',
            prerequisites: [],
            order: 2,
          },
        ],
      },
      {
        id: 'stage-monitoring',
        name: 'Monitoring & Controlling',
        description: 'Monitor and control project performance',
        status: 'in_progress',
        prerequisites: [],
        alwaysAccessible: true,
        order: 4,
        activities: [
          {
            id: 'act-dashboard',
            name: 'Project Dashboard',
            description: 'Real-time project status and KPIs',
            status: 'in_progress',
            canvasType: 'dashboard',
            artifactId: 'artifact-dashboard-1',
            prerequisites: [],
            alwaysAccessible: true,
            order: 1,
          },
          {
            id: 'act-quality-dashboard',
            name: 'Quality Dashboard',
            description: 'Quality health, coverage, and defect trends',
            status: 'in_progress',
            canvasType: 'dashboard',
            artifactId: 'artifact-quality-dashboard-1',
            prerequisites: [],
            alwaysAccessible: true,
            order: 2,
          },
          {
            id: 'act-risks',
            name: 'Risk Register',
            description: 'Track and manage project risks',
            status: 'not_started',
            canvasType: 'spreadsheet',
            prerequisites: [],
            alwaysAccessible: true,
            order: 3,
          },
          {
            id: 'act-issues',
            name: 'Issue Log',
            description: 'Track and resolve project issues',
            status: 'not_started',
            canvasType: 'spreadsheet',
            prerequisites: [],
            alwaysAccessible: true,
            order: 4,
          },
          {
            id: 'act-change-log',
            name: 'Change Log',
            description: 'Track project change requests',
            status: 'not_started',
            canvasType: 'spreadsheet',
            prerequisites: [],
            alwaysAccessible: true,
            order: 5,
          },
        ],
      },
      {
        id: 'stage-closing',
        name: 'Closing',
        description: 'Formally close the project',
        status: 'not_started',
        prerequisites: ['stage-execution'],
        order: 5,
        activities: [
          {
            id: 'act-lessons',
            name: 'Lessons Learned',
            description: 'Document lessons learned for future projects',
            status: 'not_started',
            canvasType: 'document',
            prerequisites: [],
            order: 1,
          },
          {
            id: 'act-closeout',
            name: 'Project Closeout Report',
            description: 'Final project report and closure documentation',
            status: 'not_started',
            canvasType: 'document',
            prerequisites: ['act-lessons'],
            order: 2,
          },
        ],
      },
    ],
  },
  currentActivityId: 'act-schedule',
  expandedStageIds: ['stage-initiation', 'stage-planning', 'stage-monitoring'],
};

/**
 * Available methodology templates
 */
export const methodologyTemplates: MethodologyMap[] = [
  waterfallMethodology,
  agileMethodology,
  hybridMethodology,
];
