source: project
schema: project
target: jira_project
fields:
  - source: id
    target: key
  - source: name
    target: name
  - source: status
    target: status
  - source: owner
    target: lead.displayName
  - source: benefits_realisation_plan
    target: customfield_benefits_realisation_plan
  - source: regulatory_category
    target: customfield_regulatory_category
