replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.95.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    grpc: 4317
    http: 4318
    prometheus: 8889

collectorConfig:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
  exporters:
    azuremonitor:
      connection_string: "${AZURE_MONITOR_CONNECTION_STRING}"
    jaeger:
      endpoint: "${JAEGER_COLLECTOR_ENDPOINT}"
      tls:
        insecure: true
    loki:
      endpoint: "${LOKI_ENDPOINT}"
      tls:
        insecure: true
    logging:
      loglevel: info
    prometheus:
      endpoint: "0.0.0.0:8889"
      resource_to_telemetry_conversion:
        enabled: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [jaeger, azuremonitor, logging]
      metrics:
        receivers: [otlp]
        exporters: [prometheus, azuremonitor, logging]
      logs:
        receivers: [otlp]
        exporters: [loki, azuremonitor, logging]
