apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app.kubernetes.io/name: otel-collector

data:
  otel-collector-config.yaml: |
{{- toYaml .Values.config | nindent 4 }}
