apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-kv
  labels:
    app.kubernetes.io/name: otel-collector
  annotations:
    azure.workload.identity/client-id: {{ required "keyVault.clientId is required for otel-collector" .Values.keyVault.clientId | quote }}
