global:
  image:
    pullPolicy: IfNotPresent
  env:
    LOG_LEVEL: "INFO"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector:4318/v1/metrics"

audit-log:
  keyVault:
    name: "ppm-kv"
    tenantId: "00000000-0000-0000-0000-000000000000"
    clientId: "00000000-0000-0000-0000-000000000000"
