name: IaC Scan

on:
  pull_request:
    paths:
      - "ops/infra/**"
      - "**/*.tf"
      - "**/*.tfvars"
      - "ops/infra/kubernetes/**"
      - "**/helm/**"
  push:
    branches: [main]
    paths:
      - "ops/infra/**"
      - "**/*.tf"
      - "**/*.tfvars"
      - "ops/infra/kubernetes/**"
      - "**/helm/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@8c8d7b3d1f5f9971d9ab57d1b0b6f7d2d9b9e01d
        with:
          directory: infra
